server:
  port: 8085
  compression:
    enabled: 'true'
    mime-types: text/html,text/css,application/javascript,application/json,application/font-sfnt,application/font-woff,application/font-woff2
  servlet:
    encoding:
      charset: UTF-8

spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    password: '123456'
    username: postgres
    url: jdbc:postgresql://localhost:5432/green_plate
  flyway:
    locations: classpath:db.migration
  sql:
    init:
      encoding: UTF-8

springdoc:
  api-docs:
    path: /api-docs
authentication:
  jwtToken:
    secret: '123456789'

gcp:
  config:
    file: green-plate-398515-5d6cf198ab5f.json
  project:
    id: green-plate-398515
  bucket:
    id: green_plate_main_bucket_287589
  dir:
    name: dev
